<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="nor-atuls-lt" failures="2" tests="3" name="test Test" time="32.375" errors="0" timestamp="2021-08-08T00:31:48 EDT">
  <testcase classname="com.trax.testCases.TC_LoginPassFail" name="LoginPassFail" time="8.76">
    <failure type="java.lang.AssertionError" message="expected [http://automationpractice.com/index.php?controller=my-account] but found [http://automationpractice.com/index.php?controller=authentication]">
      <![CDATA[java.lang.AssertionError: expected [http://automationpractice.com/index.php?controller=my-account] but found [http://automationpractice.com/index.php?controller=authentication]
at com.trax.pageObjects.HomePage.loginUnamePwd(HomePage.java:182)
at com.trax.testCases.TC_LoginPassFail.LoginPassFail(TC_LoginPassFail.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- LoginPassFail -->
  <testcase classname="com.trax.testCases.TC_LoginPassFail" name="LoginPassFail" time="9.524">
    <failure type="java.lang.AssertionError" message="expected [http://automationpractice.com/index.php?controller=my-account] but found [http://automationpractice.com/index.php?controller=authentication]">
      <![CDATA[java.lang.AssertionError: expected [http://automationpractice.com/index.php?controller=my-account] but found [http://automationpractice.com/index.php?controller=authentication]
at com.trax.pageObjects.HomePage.loginUnamePwd(HomePage.java:182)
at com.trax.testCases.TC_LoginPassFail.LoginPassFail(TC_LoginPassFail.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- LoginPassFail -->
  <testcase classname="com.trax.testCases.TC_LoginPassFail" name="LoginPassFail" time="8.504"/>
</testsuite> <!-- test Test -->
